In [1]:
import tensorflow as tf
import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("/content/Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
data.shape

(10000, 14)

In [4]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [5]:
data['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [6]:
data['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [7]:
X = data.drop(columns = ['RowNumber','CustomerId','Surname'])
Y = data['Exited']

In [8]:
X.head()

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [9]:
X.shape

(10000, 11)

In [10]:
Y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
label1 = LabelEncoder()
X['Geography'] = label1.fit_transform(X['Geography'])
label2 = LabelEncoder()
X['Gender'] = label2.fit_transform(X['Gender'])

In [12]:
X.head()

CreditScore  Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619          0       0  ...               1        101348.88       1
1          608          2       0  ...               1        112542.58       0
2          502          0       0  ...               0        113931.57       1
3          699          0       0  ...               0         93826.63       0
4          850          2       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [13]:
X.shape

(10000, 11)

In [14]:
X = pd.get_dummies(X,columns = ['Geography'],drop_first=True)
X.head()

CreditScore  Gender  Age  ...  Exited  Geography_1  Geography_2
0          619       0   42  ...       1            0            0
1          608       0   41  ...       0            0            1
2          502       0   42  ...       1            0            0
3          699       0   39  ...       0            0            0
4          850       0   43  ...       0            0            1

[5 rows x 12 columns]

In [15]:
X.shape

(10000, 12)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(X,Y,test_size = 0.2,random_state = 0,stratify = Y)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
x_train[:5]

array([[-1.24021723, -1.09665089,  0.77986083,  0.35390313, -1.23451386,
        -0.90298067, -1.54963239, -1.03849022,  1.64099027,  1.97686   ,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717,  0.35390313,  0.2854211 ,
         0.81371262,  0.64531434,  0.96293637, -1.55587522, -0.50585272,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , -0.3390904 ,  0.85569573,
        -0.90298067,  0.64531434, -1.03849022,  1.1038111 , -0.50585272,
        -0.57812007, -0.57504086],
       [ 0.04473499,  0.91186722, -0.17803735,  0.35390313,  0.5180063 ,
         0.81371262,  0.64531434, -1.03849022, -1.70935729, -0.50585272,
        -0.57812007, -0.57504086],
       [-1.92414341,  0.91186722, -0.56119662,  0.00740637, -1.23451386,
         0.81371262, -1.54963239,  0.96293637, -0.37557412, -0.50585272,
        -0.57812007, -0.57504086]])

In [19]:
model = keras.Sequential()
model.add(keras.layers.Dense(X.shape[1],activation = 'relu',input_dim = X.shape[1]))
model.add(keras.layers.Dense(128,activation = 'relu'))
model.add(keras.layers.Dense(1,activation = 'sigmoid'))
model.compile(loss='binary_crossentropy',optimizer= 'Adam',metrics= ['accuracy'])

In [20]:
model.fit(x_train,y_train.to_numpy(),batch_size = 10,epochs=10,verbose = 1)

Epoch 1/10
800/800 [==============================] - 15s 1ms/step - loss: 0.2295 - accuracy: 0.9074
Epoch 2/10
800/800 [==============================] - 1s 1ms/step - loss: 0.0010 - accuracy: 1.0000
Epoch 3/10
800/800 [==============================] - 1s 1ms/step - loss: 1.9136e-04 - accuracy: 1.0000
Epoch 4/10
800/800 [==============================] - 1s 1ms/step - loss: 6.8661e-05 - accuracy: 1.0000
Epoch 5/10
800/800 [==============================] - 1s 1ms/step - loss: 3.5423e-05 - accuracy: 1.0000
Epoch 6/10
800/800 [==============================] - 1s 1ms/step - loss: 1.7601e-05 - accuracy: 1.0000
Epoch 7/10
800/800 [==============================] - 1s 1ms/step - loss: 1.0892e-05 - accuracy: 1.0000
Epoch 8/10
800/800 [==============================] - 1s 1ms/step - loss: 5.9731e-06 - accuracy: 1.0000
Epoch 9/10
800/800 [==============================] - 1s 1ms/step - loss: 3.6051e-06 - accuracy: 1.0000
Epoch 10/10
800/800 [==============================] - 1s 1ms/step - lo

In [21]:
model.evaluate(x_test,y_test.to_numpy())

63/63 [==============================] - 1s 973us/step - loss: 1.7404e-06 - accuracy: 1.0000


[1.7403671108695562e-06, 1.0]

In [22]:
y_pred = model.predict_classes(x_test)
y_pred[:10]

/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0]], dtype=int32)

In [23]:
y_test.head(10)

1344    1
8167    0
4747    0
5004    1
3124    1
1940    1
2090    0
3298    0
8364    1
9485    0
Name: Exited, dtype: int64

In [24]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)

array([[1593,    0],
       [   0,  407]])

In [25]:
accuracy_score(y_test,y_pred)

1.0